version: "3"

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blogapp
      - FRONTEND_PORT=8000
      - PORT=3000
      - SECRET_KEY=MY_SECRET_KEY
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  mongo-data:
